### ISSUE TITLE
数据导入向导功能

### ISSUE THREAD

**Issue by 7168** [Zneiat/QwQuery#1]
目前导入成绩数据操作比较麻烦，能否做一个数据导入向导功能（网页上导入数据）呢？

大概思路是这样的：用户可以上传一个 excel (.xsl) 文件，程序读取并解析 .xsl 文件表头所有字段，供用户选择来指定哪一字段是什么的数据（例如有表头字段名为 `数学成绩`，用户选择这个字段，即读取这个字段的数据，并保存到数据库的字段 `sx` 中，和 FieldList.php 文件 FN 对应）

[https://github.com/qwqcode/QwQuery/blob/master/app/FieldList.php](https://github.com/qwqcode/QwQuery/blob/master/app/FieldList.php)

**Comment by qwqcode** [comment]
目前导入数据可以借助 Navicat 等数据库管理软件解析 .xsl，考虑到这样确实操作不太方便，以后有空会加入这个功能，敬请期待 😁

**Comment by Ebxh** [comment]
功能+1  期待update

**Comment by CrazyBoyM** [comment]
镜像源已经关了，请修改composer.lock

**Comment by CrazyBoyM** [comment]
默认数据库文件能不能给一份

**Comment by CrazyBoyM** [comment]
已捐赠，支持一下

**Comment by qwqcode** [comment]
代码太乱了
so... 我决定重写 qwq
emmm... 前后端采用 TypeScript+Vue
-> 支持表格数据直接导入 无需SQL数据库

https://github.com/qwqcode/qwquiver

正在开发中... （当前为高中开学状态，缓慢更新....） TAT

**Comment by qwqcode** [comment]
- 本项目已用 Golang 重写
- 项目名由 qwquery 改为 qwquiver
- 增加成绩 Excel 表格 `.xlsx` 文件一键导入功能（目前仅开发完成 CLI 命令行版本）
